### PR TITLE
rom/lifecycle: release transition mutex on error paths

### LINKED ISSUE #1223: [Bug] Lifecycle transition mutex not released on error paths
In ```lifecycle.rs```, the ```Lifecycle::transition()``` function acquires the claim_transition_if mutex before initiating a lifecycle state transition but fails to release it when the transition encounters an error.

The polling loop at Step 7 uses ```return Err(...)``` for all error conditions which exits the function immediately. The mutex release (```self.registers.claim_transition_if.set(0)```) only executes after the loop on the success path.

This means any failed lifecycle transition will leave the claim_transition_if mutex permanently held, preventing any subsequent transition attempts from acquiring it.

Also, the steps jump from 1 to 3, 4, 6, 7 - missing 2, 5, and the release step is unnumbered

### PR DESCRIPTION
**Pull request by giladliber**
Introduce TransitionMutexGuard to ensure the lifecycle transition mutex is always released when the function returns, including on error paths.
This replaces the manual release at the end of transition() and allows using early returns instead of break statements in the status polling loop.

Fixes #1223

### CODE REVIEW

File: rom/src/lifecycle.rs [hunk 1]
```diff
@@ -124,89 +124,92 @@ impl Lifecycle {
...
             if status.is_set(lc_ctrl::bits::Status::OtpPartitionError) {
-                caliptra_mcu_romtime::println!("[mcu-rom-lcc] OTP partition error detected.");
-                return Err(McuError::ROM_LC_OTP_PARTITION_ERROR);
+                romtime::println!("[mcu-rom-lcc] OTP partition error detected.");
+                break Err(McuError::ROM_LC_OTP_PARTITION_ERROR);
             }
-        }
+        };
 
+        // Step 6: Release the mutex, regardless of success or failure
```
Comment (clundin25) [inline rom/src/lifecycle.rs]: Does it make sense to wrap this in a type that releases the mutex on drop?

Comment (giladliber) [reply rom/src/lifecycle.rs]: Yes, that makes sense indeed. Then we can use "return" also for the Ok case exactly like in the Err cases.
I'll update the PR. Thanks!

Comment (clundin25) [reply rom/src/lifecycle.rs]: Thanks! If it turns into a larger refactor we can revisit, using a type seems like a good approach to prevent occurrences of this bug

Comment (giladliber) [reply rom/src/lifecycle.rs]: Updated. Let me know if that's ok and according to your coding guidelines.

**Review by clundin25 — APPROVED** [review]

**Comment by clundin25** [comment]
@giladliber looks like there are some merge conflicts, do you mind taking a look?

File: rom/src/lifecycle.rs [hunk 2]
```diff
@@ -111,102 +141,86 @@ impl Lifecycle {
...
+        romtime::println!(
             "[mcu-rom-lcc] Transitioning Lifecycle state... to {}",
             u8::from(state)
         );
         let next_lc_state_mne = Self::calc_lc_state_mnemonic(state);
         let token = u128::from_le_bytes(token.0);
 
-        const MULTI_TRUE: u32 = 0x96;
+        // Step 1: Acquire the transition mutex (released on drop)
+        let _mutex = TransitionMutexGuard::claim(self.registers);
```
Comment (clundin25) [inline rom/src/lifecycle.rs]: This mutex could be passed to a function that wraps the protected block? That makes it clear to the reader why and where it is held

**Review by zhalvorsen — APPROVED** [review]

File: rom/src/lifecycle.rs (hunk 2 above)
Comment (giladliber) [reply rom/src/lifecycle.rs]: Done. Is that what you meant?

Comment (clundin25) [reply rom/src/lifecycle.rs]: Looks great! Thanks @giladliber !

**Comment by RaunakGu** [comment]
@clundin25 - Could you please also port this to main-2.1?

**Comment by clundin25** [comment]
@RaunakGu will do 👍
